"""Protocol-level constants and default configuration values."""

from __future__ import annotations

from enum import IntEnum
from typing import Final

from pywebtransport import _pywebtransport

__all__: list[str] = [
    "DEFAULT_ALPN_PROTOCOLS",
    "DEFAULT_BIND_HOST",
    "DEFAULT_CLOSE_TIMEOUT",
    "DEFAULT_CONGESTION_CONTROL_ALGORITHM",
    "DEFAULT_CONNECTION_ATTEMPT_DELAY",
    "DEFAULT_CONNECTION_IDLE_TIMEOUT",
    "DEFAULT_CONNECT_TIMEOUT",
    "DEFAULT_DEV_PORT",
    "DEFAULT_EVENT_HISTORY_CAPACITY",
    "DEFAULT_EVENT_QUEUE_CAPACITY",
    "DEFAULT_FLOW_CONTROL_WINDOW",
    "DEFAULT_FLOW_CONTROL_WINDOW_AUTO_SCALE_ENABLED",
    "DEFAULT_INITIAL_MAX_DATA",
    "DEFAULT_INITIAL_MAX_STREAMS_BIDI",
    "DEFAULT_INITIAL_MAX_STREAMS_UNI",
    "DEFAULT_KEEP_ALIVE_INTERVAL",
    "DEFAULT_LOG_LEVEL",
    "DEFAULT_MAX_CAPSULE_SIZE",
    "DEFAULT_MAX_CONNECTIONS",
    "DEFAULT_MAX_DATAGRAM_SIZE",
    "DEFAULT_MAX_EVENT_LISTENERS",
    "DEFAULT_MAX_FIELD_SECTION_SIZE",
    "DEFAULT_MAX_SESSION_PENDING_EVENTS",
    "DEFAULT_MAX_SESSIONS",
    "DEFAULT_MAX_STREAM_READ_BUFFER_SIZE",
    "DEFAULT_MAX_STREAM_WRITE_BUFFER_SIZE",
    "DEFAULT_MAX_TOTAL_PENDING_EVENTS",
    "DEFAULT_MAX_TRANSPORT_STREAMS",
    "DEFAULT_PENDING_EVENT_TTL",
    "DEFAULT_READ_TIMEOUT",
    "DEFAULT_RESOURCE_CLEANUP_INTERVAL",
    "DEFAULT_STREAM_CREATION_TIMEOUT",
    "DEFAULT_WRITE_TIMEOUT",
    "ErrorCodes",
    "UDP_MAX_DATAGRAM_SIZE",
    "WT_STREAMS_LIMIT",
]

DEFAULT_ALPN_PROTOCOLS: Final[list[str]] = _pywebtransport.DEFAULT_ALPN_PROTOCOLS
DEFAULT_BIND_HOST: Final[str] = _pywebtransport.DEFAULT_BIND_HOST
DEFAULT_CLOSE_TIMEOUT: Final[float] = _pywebtransport.DEFAULT_CLOSE_TIMEOUT
DEFAULT_CONGESTION_CONTROL_ALGORITHM: Final[str] = _pywebtransport.DEFAULT_CONGESTION_CONTROL_ALGORITHM
DEFAULT_CONNECTION_ATTEMPT_DELAY: Final[float] = _pywebtransport.DEFAULT_CONNECTION_ATTEMPT_DELAY
DEFAULT_CONNECTION_IDLE_TIMEOUT: Final[float] = _pywebtransport.DEFAULT_CONNECTION_IDLE_TIMEOUT
DEFAULT_CONNECT_TIMEOUT: Final[float] = _pywebtransport.DEFAULT_CONNECT_TIMEOUT
DEFAULT_DEV_PORT: Final[int] = _pywebtransport.DEFAULT_DEV_PORT
DEFAULT_EVENT_HISTORY_CAPACITY: Final[int] = _pywebtransport.DEFAULT_EVENT_HISTORY_CAPACITY
DEFAULT_EVENT_QUEUE_CAPACITY: Final[int] = _pywebtransport.DEFAULT_EVENT_QUEUE_CAPACITY
DEFAULT_FLOW_CONTROL_WINDOW: Final[int] = _pywebtransport.DEFAULT_FLOW_CONTROL_WINDOW
DEFAULT_FLOW_CONTROL_WINDOW_AUTO_SCALE_ENABLED: Final[bool] = (
    _pywebtransport.DEFAULT_FLOW_CONTROL_WINDOW_AUTO_SCALE_ENABLED
)
DEFAULT_INITIAL_MAX_DATA: Final[int] = _pywebtransport.DEFAULT_INITIAL_MAX_DATA
DEFAULT_INITIAL_MAX_STREAMS_BIDI: Final[int] = _pywebtransport.DEFAULT_INITIAL_MAX_STREAMS_BIDI
DEFAULT_INITIAL_MAX_STREAMS_UNI: Final[int] = _pywebtransport.DEFAULT_INITIAL_MAX_STREAMS_UNI
DEFAULT_KEEP_ALIVE_INTERVAL: Final[float] = _pywebtransport.DEFAULT_KEEP_ALIVE_INTERVAL
DEFAULT_LOG_LEVEL: Final[str] = _pywebtransport.DEFAULT_LOG_LEVEL
DEFAULT_MAX_CAPSULE_SIZE: Final[int] = _pywebtransport.DEFAULT_MAX_CAPSULE_SIZE
DEFAULT_MAX_CONNECTIONS: Final[int] = _pywebtransport.DEFAULT_MAX_CONNECTIONS
DEFAULT_MAX_DATAGRAM_SIZE: Final[int] = _pywebtransport.DEFAULT_MAX_DATAGRAM_SIZE
DEFAULT_MAX_EVENT_LISTENERS: Final[int] = _pywebtransport.DEFAULT_MAX_EVENT_LISTENERS
DEFAULT_MAX_FIELD_SECTION_SIZE: Final[int] = _pywebtransport.DEFAULT_MAX_FIELD_SECTION_SIZE
DEFAULT_MAX_SESSION_PENDING_EVENTS: Final[int] = _pywebtransport.DEFAULT_MAX_SESSION_PENDING_EVENTS
DEFAULT_MAX_SESSIONS: Final[int] = _pywebtransport.DEFAULT_MAX_SESSIONS
DEFAULT_MAX_STREAM_READ_BUFFER_SIZE: Final[int] = _pywebtransport.DEFAULT_MAX_STREAM_READ_BUFFER_SIZE
DEFAULT_MAX_STREAM_WRITE_BUFFER_SIZE: Final[int] = _pywebtransport.DEFAULT_MAX_STREAM_WRITE_BUFFER_SIZE
DEFAULT_MAX_TOTAL_PENDING_EVENTS: Final[int] = _pywebtransport.DEFAULT_MAX_TOTAL_PENDING_EVENTS
DEFAULT_MAX_TRANSPORT_STREAMS: Final[int] = _pywebtransport.DEFAULT_MAX_TRANSPORT_STREAMS
DEFAULT_PENDING_EVENT_TTL: Final[float] = _pywebtransport.DEFAULT_PENDING_EVENT_TTL
DEFAULT_READ_TIMEOUT: Final[float] = _pywebtransport.DEFAULT_READ_TIMEOUT
DEFAULT_RESOURCE_CLEANUP_INTERVAL: Final[float] = _pywebtransport.DEFAULT_RESOURCE_CLEANUP_INTERVAL
DEFAULT_STREAM_CREATION_TIMEOUT: Final[float] = _pywebtransport.DEFAULT_STREAM_CREATION_TIMEOUT
DEFAULT_WRITE_TIMEOUT: Final[float] = _pywebtransport.DEFAULT_WRITE_TIMEOUT
UDP_MAX_DATAGRAM_SIZE: Final[int] = _pywebtransport.UDP_MAX_DATAGRAM_SIZE
WT_STREAMS_LIMIT: Final[int] = _pywebtransport.WT_STREAMS_LIMIT


class ErrorCodes(IntEnum):
    """Enumeration of WebTransport and HTTP/3 error codes."""

    APP_AUTHENTICATION_FAILED = _pywebtransport.ERR_APP_AUTHENTICATION_FAILED
    APP_CANCELLED = _pywebtransport.ERR_APP_CANCELLED
    APP_CONNECTION_TIMEOUT = _pywebtransport.ERR_APP_CONNECTION_TIMEOUT
    APP_GENERIC_ERROR = _pywebtransport.ERR_APP_GENERIC_ERROR
    APP_INVALID_REQUEST = _pywebtransport.ERR_APP_INVALID_REQUEST
    APP_NO_ERROR = _pywebtransport.ERR_APP_NO_ERROR
    APP_OPERATION_TIMEOUT = _pywebtransport.ERR_APP_OPERATION_TIMEOUT
    APP_PERMISSION_DENIED = _pywebtransport.ERR_APP_PERMISSION_DENIED
    APP_RESOURCE_EXHAUSTED = _pywebtransport.ERR_APP_RESOURCE_EXHAUSTED
    APP_SERVICE_UNAVAILABLE = _pywebtransport.ERR_APP_SERVICE_UNAVAILABLE
    H3_CLOSED_CRITICAL_STREAM = _pywebtransport.ERR_H3_CLOSED_CRITICAL_STREAM
    H3_CONNECT_ERROR = _pywebtransport.ERR_H3_CONNECT_ERROR
    H3_DATAGRAM_ERROR = _pywebtransport.ERR_H3_DATAGRAM_ERROR
    H3_EXCESSIVE_LOAD = _pywebtransport.ERR_H3_EXCESSIVE_LOAD
    H3_FRAME_ERROR = _pywebtransport.ERR_H3_FRAME_ERROR
    H3_FRAME_UNEXPECTED = _pywebtransport.ERR_H3_FRAME_UNEXPECTED
    H3_GENERAL_PROTOCOL_ERROR = _pywebtransport.ERR_H3_GENERAL_PROTOCOL_ERROR
    H3_ID_ERROR = _pywebtransport.ERR_H3_ID_ERROR
    H3_INTERNAL_ERROR = _pywebtransport.ERR_H3_INTERNAL_ERROR
    H3_MESSAGE_ERROR = _pywebtransport.ERR_H3_MESSAGE_ERROR
    H3_MISSING_SETTINGS = _pywebtransport.ERR_H3_MISSING_SETTINGS
    H3_NO_ERROR = _pywebtransport.ERR_H3_NO_ERROR
    H3_REQUEST_CANCELLED = _pywebtransport.ERR_H3_REQUEST_CANCELLED
    H3_REQUEST_INCOMPLETE = _pywebtransport.ERR_H3_REQUEST_INCOMPLETE
    H3_REQUEST_REJECTED = _pywebtransport.ERR_H3_REQUEST_REJECTED
    H3_SETTINGS_ERROR = _pywebtransport.ERR_H3_SETTINGS_ERROR
    H3_STREAM_CREATION_ERROR = _pywebtransport.ERR_H3_STREAM_CREATION_ERROR
    H3_VERSION_FALLBACK = _pywebtransport.ERR_H3_VERSION_FALLBACK
    LIB_CONNECTION_STATE_ERROR = _pywebtransport.ERR_LIB_CONNECTION_STATE_ERROR
    LIB_INTERNAL_ERROR = _pywebtransport.ERR_LIB_INTERNAL_ERROR
    LIB_SESSION_STATE_ERROR = _pywebtransport.ERR_LIB_SESSION_STATE_ERROR
    LIB_STREAM_STATE_ERROR = _pywebtransport.ERR_LIB_STREAM_STATE_ERROR
    QPACK_DECODER_STREAM_ERROR = _pywebtransport.ERR_QPACK_DECODER_STREAM_ERROR
    QPACK_DECOMPRESSION_FAILED = _pywebtransport.ERR_QPACK_DECOMPRESSION_FAILED
    QPACK_ENCODER_STREAM_ERROR = _pywebtransport.ERR_QPACK_ENCODER_STREAM_ERROR
    QUIC_AEAD_LIMIT_REACHED = _pywebtransport.ERR_QUIC_AEAD_LIMIT_REACHED
    QUIC_APPLICATION_ERROR = _pywebtransport.ERR_QUIC_APPLICATION_ERROR
    QUIC_CONNECTION_ID_LIMIT_ERROR = _pywebtransport.ERR_QUIC_CONNECTION_ID_LIMIT_ERROR
    QUIC_CONNECTION_REFUSED = _pywebtransport.ERR_QUIC_CONNECTION_REFUSED
    QUIC_CRYPTO_BUFFER_EXCEEDED = _pywebtransport.ERR_QUIC_CRYPTO_BUFFER_EXCEEDED
    QUIC_FINAL_SIZE_ERROR = _pywebtransport.ERR_QUIC_FINAL_SIZE_ERROR
    QUIC_FLOW_CONTROL_ERROR = _pywebtransport.ERR_QUIC_FLOW_CONTROL_ERROR
    QUIC_FRAME_ENCODING_ERROR = _pywebtransport.ERR_QUIC_FRAME_ENCODING_ERROR
    QUIC_INTERNAL_ERROR = _pywebtransport.ERR_QUIC_INTERNAL_ERROR
    QUIC_INVALID_TOKEN = _pywebtransport.ERR_QUIC_INVALID_TOKEN
    QUIC_KEY_UPDATE_ERROR = _pywebtransport.ERR_QUIC_KEY_UPDATE_ERROR
    QUIC_NO_ERROR = _pywebtransport.ERR_QUIC_NO_ERROR
    QUIC_NO_VIABLE_PATH = _pywebtransport.ERR_QUIC_NO_VIABLE_PATH
    QUIC_PROTOCOL_VIOLATION = _pywebtransport.ERR_QUIC_PROTOCOL_VIOLATION
    QUIC_STREAM_LIMIT_ERROR = _pywebtransport.ERR_QUIC_STREAM_LIMIT_ERROR
    QUIC_STREAM_STATE_ERROR = _pywebtransport.ERR_QUIC_STREAM_STATE_ERROR
    QUIC_TRANSPORT_PARAMETER_ERROR = _pywebtransport.ERR_QUIC_TRANSPORT_PARAMETER_ERROR
    WT_ALPN_ERROR = _pywebtransport.ERR_WT_ALPN_ERROR
    WT_APPLICATION_ERROR_FIRST = _pywebtransport.ERR_WT_APPLICATION_ERROR_FIRST
    WT_APPLICATION_ERROR_LAST = _pywebtransport.ERR_WT_APPLICATION_ERROR_LAST
    WT_BUFFERED_STREAM_REJECTED = _pywebtransport.ERR_WT_BUFFERED_STREAM_REJECTED
    WT_FLOW_CONTROL_ERROR = _pywebtransport.ERR_WT_FLOW_CONTROL_ERROR
    WT_REQUIREMENTS_NOT_MET = _pywebtransport.ERR_WT_REQUIREMENTS_NOT_MET
    WT_SESSION_GONE = _pywebtransport.ERR_WT_SESSION_GONE
